# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem "tty-prompt"
gem "tty-table"
gem "simple-random"
gem "table_print"
gem "tty-box"
gem "rainbow"
gem "colorize"
gem "tty-font"